# Adv Data Acq

Quick exploration to see what cleaning if any needs to be done.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('medical_clean.csv')

In [3]:
df.sample(10).T

,8266,7957,7597,4196,6569,7261,3256,104,2302,6151
CaseOrder,8267,7958,7598,4197,6570,7262,3257,105,2303,6152
Customer_id,O603622,R179125,I214629,R41521,A700309,I46912,R130898,R457596,K18682,X309453
Interaction,ac583fb1-1607-4403-9d0a-b2c9dadcb9c8,299c60e7-1ebc-46e5-af0e-770515d44fea,dede8c86-c6a1-46cc-a547-f5eb775f0ed4,532ba43c-3f22-4c2e-bec5-d30c9e69c28c,9f983195-ae18-4280-ad87-bbc1d71c7aa4,a30586ee-7858-4ddf-9ec4-7c0d4b4aabae,d906c10d-f8ec-4c22-97ea-40af21ce99a8,05775b04-064e-4cae-95f2-76b2f3bfba82,99e66e82-6f39-4b7a-973b-23ae1384ebe9,8ae220ee-4fce-4029-ba91-7b6a77ed2191
UID,1b91b2d5967e1b2e55c488ae58a6c83a,fb8783cdaea24d7b85aa28261d5aea6c,d9fadc42aadf79aa02dc25e25ba8e768,018ba4ac94a0a3c2ac5e518ed5efb126,0bafc3d5c332947a01f4d63bf1851078,70421d2d9f99dca2038d032457480ab2,a8acbff50c85f93e17601af58dc13137,202195bc01f9f8047311ae34b77e1c44,54cffaf81fe92a1ceaea45d23442af47,5af0e89b3382c3f1896f896429b3b205
City,Garden City,East Saint Louis,Hartsburg,Sullivan,Saint Joseph,Hartford,New Market,Lees Summit,Whitesburg,Caddo Mills
State,UT,IL,MO,OH,MI,CT,IA,MO,TN,TX
County,Rich,St. Clair,Boone,Ashland,Berrien,Hartford,Taylor,Jackson,Hamblen,Hunt
Zip,84028,62207,65039,44880,49085,6106,51646,64086,37891,75135
Lat,41.93362,38.58284,38.71068,41.03412,42.05012,41.74867,40.74654,38.90788,36.29001,33.06522
Lng,-111.4055,-90.12291,-92.28724,-82.22035,-86.46029,-72.69495,-94.87586,-94.28753,-83.13771,-96.22289
Population,793,8913,2709,2844,23716,37819,716,23177,2850,7725
Area,Rural,Rural,Urban,Urban,Suburban,Rural,Urban,Rural,Urban,Suburban
TimeZone,America/Denver,America/Chicago,America/Chicago,America/New_York,America/Detroit,America/New_York,America/Chicago,America/Chicago,America/New_York,America/Chicago
Job,Make,"Geneticist, molecular","Investment banker, corporate",Marketing executive,Merchant navy officer,Commercial art gallery manager,Toxicologist,Hospital doctor,Hydrogeologist,Psychiatrist
Children,7,0,0,3,1,2,0,2,2,4
Age,50,36,23,30,52,26,58,24,29,55
Income,13347.46,4146.15,43071.76,37556.4,15457.75,49117.05,10037.7,23180.9,99822.0,29317.17
Marital,Widowed,Never Married,Separated,Widowed,Never Married,Widowed,Never Married,Married,Divorced,Married
Gender,Male,Male,Female,Female,Male,Male,Female,Female,Female,Female
ReAdmis,Yes,No,Yes,No,Yes,Yes,No,No,No,Yes
VitD_levels,18.62124,20.01166,18.16785,15.501666,13.9486,17.2147,15.446849,16.009449,18.164869,18.61788
Doc_visits,7,5,6,6,5,5,6,4,4,5
Full_meals_eaten,0,2,2,1,2,0,1,1,1,0
vitD_supp,1,0,0,2,0,1,1,0,0,0
Soft_drink,No,Yes,No,No,No,No,No,No,No,No
Initial_admin,Elective Admission,Emergency Admission,Emergency Admission,Emergency Admission,Emergency Admission,Observation Admission,Emergency Admission,Elective Admission,Observation Admission,Emergency Admission
HighBlood,Yes,No,No,Yes,No,No,No,No,No,No
Stroke,Yes,No,Yes,Yes,No,Yes,No,No,No,No
Complication_risk,High,Low,Medium,Medium,High,High,High,Low,Medium,Medium
Overweight,Yes,No,No,Yes,No,Yes,Yes,Yes,Yes,Yes
Arthritis,No,No,Yes,No,No,Yes,No,Yes,Yes,No
Diabetes,No,No,Yes,No,No,Yes,No,No,No,No
Hyperlipidemia,No,No,No,Yes,No,Yes,Yes,No,No,Yes
BackPain,Yes,No,No,No,No,No,Yes,No,No,Yes
Anxiety,No,Yes,No,No,No,No,No,Yes,Yes,No
Allergic_rhinitis,Yes,No,No,No,No,No,Yes,Yes,Yes,Yes
Reflux_esophagitis,Yes,No,No,No,Yes,Yes,Yes,No,No,Yes
Asthma,Yes,No,No,No,No,Yes,Yes,No,No,No
Services,Blood Work,Blood Work,Blood Work,CT Scan,Intravenous,Blood Work,CT Scan,Blood Work,Intravenous,Blood Work
Initial_days,66.62136,52.00942,62.71224,19.821392,63.51076,67.04683,11.150493,1.032976,16.230715,67.27822
TotalCharge,8045.721,6715.663,7653.668,4198.44446,8045.118,8063.677,3994.548008,2158.971959,3404.241882,8180.039
Additional_charges,17178.66,6436.214,5099.868,11103.39097,9578.681,5183.525,10425.81835,4075.029933,5010.256673,9660.429
Item1,3,4,3,4,4,4,4,4,2,3
Item2,3,4,1,4,5,3,4,5,1,4
Item3,4,5,3,4,3,3,3,5,2,3
Item4,3,4,3,3,2,4,3,5,4,3
Item5,5,4,4,3,5,4,4,4,3,1
Item6,3,3,3,5,2,2,4,4,3,4
Item7,4,4,2,5,4,3,3,4,3,3
Item8,2,3,3,4,3,5,2,4,4,4

In [4]:
for i in df.columns:
    if df[i].nunique() <=10:
        print(f'Column {i}')
        print(df[i].value_counts())
        print('-------')

Column Area
Rural       3369
Suburban    3328
Urban       3303
Name: Area, dtype: int64
-------
Column Marital
Widowed          2045
Married          2023
Separated        1987
Never Married    1984
Divorced         1961
Name: Marital, dtype: int64
-------
Column Gender
Female       5018
Male         4768
Nonbinary     214
Name: Gender, dtype: int64
-------
Column ReAdmis
No     6331
Yes    3669
Name: ReAdmis, dtype: int64
-------
Column Doc_visits
5    3823
6    2436
4    2385
7     634
3     595
8      61
2      58
1       6
9       2
Name: Doc_visits, dtype: int64
-------
Column Full_meals_eaten
0    3715
1    3615
2    1856
3     612
4     169
5      25
6       6
7       2
Name: Full_meals_eaten, dtype: int64
-------
Column vitD_supp
0    6702
1    2684
2     544
3      64
4       5
5       1
Name: vitD_supp, dtype: int64
-------
Column Soft_drink
No     7425
Yes    2575
Name: Soft_drink, dtype: int64
-------
Column Initial_admin
Emergency Admission      5060
Elective Admission       2504
Observation Admission    2436
Name: Initial_admin, dtype: int64
-------
Column HighBlood
No     5910
Yes    4090
Name: HighBlood, dtype: int64
-------
Column Stroke
No     8007
Yes    1993
Name: Stroke, dtype: int64
-------
Column Complication_risk
Medium    4517
High      3358
Low       2125
Name: Complication_risk, dtype: int64
-------
Column Overweight
Yes    7094
No     2906
Name: Overweight, dtype: int64
-------
Column Arthritis
No     6426
Yes    3574
Name: Arthritis, dtype: int64
-------
Column Diabetes
No     7262
Yes    2738
Name: Diabetes, dtype: int64
-------
Column Hyperlipidemia
No     6628
Yes    3372
Name: Hyperlipidemia, dtype: int64
-------
Column BackPain
No     5886
Yes    4114
Name: BackPain, dtype: int64
-------
Column Anxiety
No     6785
Yes    3215
Name: Anxiety, dtype: int64
-------
Column Allergic_rhinitis
No     6059
Yes    3941
Name: Allergic_rhinitis, dtype: int64
-------
Column Reflux_esophagitis
No     5865
Yes    4135
Name: Reflux_esophagitis, dtype: int64
-------
Column Asthma
No     7107
Yes    2893
Name: Asthma, dtype: int64
-------
Column Services
Blood Work     5265
Intravenous    3130
CT Scan        1225
MRI             380
Name: Services, dtype: int64
-------
Column Item1
4    3455
3    3404
5    1377
2    1315
6     225
1     213
7      10
8       1
Name: Item1, dtype: int64
-------
Column Item2
3    3439
4    3351
5    1421
2    1360
1     213
6     204
7      12
Name: Item2, dtype: int64
-------
Column Item3
4    3464
3    3379
5    1358
2    1356
6     220
1     211
7      11
8       1
Name: Item3, dtype: int64
-------
Column Item4
3    3422
4    3394
5    1388
2    1346
6     231
1     207
7      12
Name: Item4, dtype: int64
-------
Column Item5
4    3446
3    3423
2    1380
5    1308
6     219
1     211
7      13
Name: Item5, dtype: int64
-------
Column Item6
4    3464
3    3371
5    1403
2    1319
6     220
1     213
7      10
Name: Item6, dtype: int64
-------
Column Item7
4    3487
3    3456
2    1345
5    1274
1     215
6     212
7      11
Name: Item7, dtype: int64
-------
Column Item8
3    3401
4    3337
5    1429
2    1391
6     221
1     209
7      12
Name: Item8, dtype: int64
-------

In [5]:
df.isna().sum()

CaseOrder             0
Customer_id           0
Interaction           0
UID                   0
City                  0
State                 0
County                0
Zip                   0
Lat                   0
Lng                   0
Population            0
Area                  0
TimeZone              0
Job                   0
Children              0
Age                   0
Income                0
Marital               0
Gender                0
ReAdmis               0
VitD_levels           0
Doc_visits            0
Full_meals_eaten      0
vitD_supp             0
Soft_drink            0
Initial_admin         0
HighBlood             0
Stroke                0
Complication_risk     0
Overweight            0
Arthritis             0
Diabetes              0
Hyperlipidemia        0
BackPain              0
Anxiety               0
Allergic_rhinitis     0
Reflux_esophagitis    0
Asthma                0
Services              0
Initial_days          0
TotalCharge           0
Additional_charges    0
Item1                 0
Item2                 0
Item3                 0
Item4                 0
Item5                 0
Item6                 0
Item7                 0
Item8                 0
dtype: int64

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
CaseOrder,10000.0,5000.500000,2886.895680,1.000000,2500.750000,5000.500000,7500.250000,10000.000000
Zip,10000.0,50159.323900,27469.588208,610.000000,27592.000000,50207.000000,72411.750000,99929.000000
Lat,10000.0,38.751099,5.403085,17.967190,35.255120,39.419355,42.044175,70.560990
Lng,10000.0,-91.243080,15.205998,-174.209700,-97.352982,-88.397230,-80.438050,-65.290170
Population,10000.0,9965.253800,14824.758614,0.000000,694.750000,2769.000000,13945.000000,122814.000000
Children,10000.0,2.097200,2.163659,0.000000,0.000000,1.000000,3.000000,10.000000
Age,10000.0,53.511700,20.638538,18.000000,36.000000,53.000000,71.000000,89.000000
Income,10000.0,40490.495160,28521.153293,154.080000,19598.775000,33768.420000,54296.402500,207249.100000
VitD_levels,10000.0,17.964262,2.017231,9.806483,16.626439,17.951122,19.347963,26.394449
Doc_visits,10000.0,5.012200,1.045734,1.000000,4.000000,5.000000,6.000000,9.000000
Full_meals_eaten,10000.0,1.001400,1.008117,0.000000,0.000000,1.000000,2.000000,7.000000
vitD_supp,10000.0,0.398900,0.628505,0.000000,0.000000,0.000000,1.000000,5.000000
Initial_days,10000.0,34.455299,26.309341,1.001981,7.896215,35.836244,61.161020,71.981490
TotalCharge,10000.0,5312.172769,2180.393838,1938.312067,3179.374015,5213.952000,7459.699750,9180.728000
Additional_charges,10000.0,12934.528587,6542.601544,3125.703000,7986.487755,11573.977735,15626.490000,30566.070000
Item1,10000.0,3.518800,1.031966,1.000000,3.000000,4.000000,4.000000,8.000000
Item2,10000.0,3.506700,1.034825,1.000000,3.000000,3.000000,4.000000,7.000000
Item3,10000.0,3.511100,1.032755,1.000000,3.000000,4.000000,4.000000,8.000000
Item4,10000.0,3.515100,1.036282,1.000000,3.000000,4.000000,4.000000,7.000000
Item5,10000.0,3.496900,1.030192,1.000000,3.000000,3.000000,4.000000,7.000000
Item6,10000.0,3.522500,1.032376,1.000000,3.000000,4.000000,4.000000,7.000000
Item7,10000.0,3.494000,1.021405,1.000000,3.000000,3.000000,4.000000,7.000000
Item8,10000.0,3.509700,1.042312,1.000000,3.000000,3.000000,4.000000,7.000000